"""Bundle metadata (``bundle.json``) schema.

Defines the typed shape of a bundle's metadata side-car, including the
provenance / licensing block that identifies spektrafilm as the source
and surfaces citation expectations to downstream users. I/O lives with
the builder; the dataclasses here are the source of truth for shape.

The provenance defaults mirror :class:`spektrafilm.profiles.io.ProfileMetadata`
so a user receiving a LUT bundle reads the same licensing story they'd
read on the profiles that informed it.

See studies/a40_lut_system/n030_lut_package_design.md §4.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date, datetime, timezone
from importlib.metadata import PackageNotFoundError, version as distribution_version
from typing import Any

from spektrafilm_lut_creator.wires import DensityWire, LogEWire


SCHEMA_VERSION = 1

_PROJECT_URL = "https://github.com/andreavolpato/spektrafilm"
_LUT_LICENSE_URL = "https://github.com/andreavolpato/spektrafilm/blob/main/LICENSE_SPEKTRAFILM_LUT"


def _spektrafilm_version() -> str:
    """The installed spektrafilm distribution version, or ``0+unknown``."""
    try:
        return distribution_version("spektrafilm")
    except PackageNotFoundError:
        return "0+unknown"


def _lut_creator_version() -> str:
    """The lut_creator ships as part of spektrafilm today; same version."""
    return _spektrafilm_version()


def _created_iso8601() -> str:
    """UTC build timestamp in ISO 8601 (seconds resolution)."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _copyright_statement() -> str:
    return f"Copyright (c) {date.today().year} Andrea Volpato. Generated by spektrafilm."


@dataclass
class ProvenanceMeta:
    """Provenance and licensing information for a LUT bundle.

    Every bundle carries this block so downstream users (colorists,
    grading suites, archive systems) can identify spektrafilm as the
    source, comply with the project's GPL license, and cite the work
    correctly. The defaults mirror the spektrafilm profile metadata
    pattern.
    """
    spektrafilm_version: str = field(default_factory=_spektrafilm_version)
    lut_creator_version: str = field(default_factory=_lut_creator_version)
    created: str = field(default_factory=_created_iso8601)
    copyright: str = field(default_factory=_copyright_statement)
    license: str = (
        "This LUT is licensed for personal and commercial image/video use. "
        "You may share the LUT for free, but you may not sell or resell the "
        "LUT file (original or modified), or include it in paid plugins."
        "See LICENSE_SPEKTRAFILM_LUT for details."
        "A copy of the license is included in the bundle folder,"
        f"and also available at {_LUT_LICENSE_URL}."
    )
    citation: str = (
        "If you use this LUT in your work, please cite the spektrafilm "
        f"project: {_PROJECT_URL}, see CITATION.cff for details."
    )
    project_url: str = _PROJECT_URL
    notes: str = (
        "Generated by the spektrafilm LUT bundle builder. Apply with "
        "trilinear or tetrahedral interpolation in your host (DaVinci "
        "Resolve, Nuke, OCIO-aware DCC). The input and output color spaces "
        "are declared in bundle.json; do NOT apply this LUT to a signal in "
        "a different color space."
    )


@dataclass(frozen=True)
class ColorSpaceMeta:
    """One end of the bundle's color-space contract."""
    name: str
    cctf: bool  # True if the wire carries an encoded (CCTF-applied) signal


@dataclass(frozen=True)
class StocksMeta:
    """Stock identifiers used to build the bundle."""
    film: str
    prints: tuple[str, ...]  # one entry for 1-lut-combined, >=1 otherwise


@dataclass(frozen=True)
class WiresMeta:
    """Per-bundle wire constants for the four internal taps.

    Entries can be ``None`` for topologies that don't expose the
    corresponding tap (e.g. 1-lut-combined bundles need none of these
    because the intermediate taps aren't materialized as separate LUTs).
    """
    log_e_film: LogEWire | None = None
    cmy_film: DensityWire | None = None
    log_e_print: LogEWire | None = None
    cmy_print: DensityWire | None = None


@dataclass(frozen=True)
class LutFileMeta:
    """One LUT entry within a bundle."""
    role: str            # "combined" (1-lut-combined) | "film" | "print"
    path: str            # relative to the bundle root
    domain: str          # source tap name (e.g. "input_rgb", "cmy_film")
    range: str           # destination tap name (e.g. "cmy_film", "output_rgb")
    paper: str | None = None  # set for role="print"


@dataclass
class BundleMeta:
    """The full ``bundle.json`` payload."""
    schema_version: int = SCHEMA_VERSION
    name: str = ""
    topology: str = "1-lut-combined"
    # "1-lut-combined" | "2-lut-film-print" | "4-lut-film-develop-print-develop"
    resolution: int = 33
    target: str | None = None  # delivery target name, if any
    provenance: ProvenanceMeta = field(default_factory=ProvenanceMeta)
    stocks: StocksMeta | None = None
    color_spaces: dict[str, ColorSpaceMeta] = field(default_factory=dict)
    wires: WiresMeta = field(default_factory=WiresMeta)
    luts: tuple[LutFileMeta, ...] = ()
    params_snapshot: dict[str, Any] = field(default_factory=dict)
